package entidades;
// Generated 18-jul-2019 7:59:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiporeserva generated by hbm2java
 */
public class Tiporeserva  implements java.io.Serializable {


     private Integer idtiporeserva;
     private String descripcion;
     private Set reservarcitas = new HashSet(0);

    public Tiporeserva() {
    }

    public Tiporeserva(String descripcion, Set reservarcitas) {
       this.descripcion = descripcion;
       this.reservarcitas = reservarcitas;
    }
   
    public Integer getIdtiporeserva() {
        return this.idtiporeserva;
    }
    
    public void setIdtiporeserva(Integer idtiporeserva) {
        this.idtiporeserva = idtiporeserva;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getReservarcitas() {
        return this.reservarcitas;
    }
    
    public void setReservarcitas(Set reservarcitas) {
        this.reservarcitas = reservarcitas;
    }




}


